import Head from 'next/head'
import styles from '../styles/Home.module.css'
/**
 * get the data from api and pass it to the component
 * 
 */
export async function getServerSideProps() {
  const res = await fetch(`http://localhost:3000/api/issues`);
  const issuesData = await res.json();

  return {
    props: { issuesData },
  } // return the data to the component
}
export default function Home({ issuesData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to daily issue
        </h1>
        <p>{issuesData.name}</p>
        <p>{issuesData.author}</p>
        <p>{issuesData.labels.join(", ")}</p>
        <p>{issuesData.url}</p>

    
      </main>

      <footer className={styles.footer}>
        Powered by open source learners
      </footer>
    </div>
  )
}
 